import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Intro from "@/components/Intro";
import AboutMe from "@/components/AboutMe";
import Services from "@/components/Services";
import Footer from "@/components/Footer";
import GetInTouch from "@/components/GetInTouch";
import Projects from "@/components/Projects";
import Testimonial from "@/components/Testimonial";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app & tailwindcss",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Intro />
        <AboutMe />
        <Services />
        <Projects />
        <Testimonial />
        <GetInTouch />
        <Footer />

        {children}
      </body>
    </html>
  );
}
